# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Book.destroy_all
User.destroy_all
Author.destroy_all
Review.destroy_all

astronaut = Book.create(title: "An Astronaut's Guide to Life on Earth", pages: 284, year: 2013, cover_url: 'http://media.npr.org/assets/bakertaylor/covers/a/an-astronauts-guide-to-life-on-earth/9780316253017_custom-72b5b1e3d259fb604fee1401424db3c8cd04cfe0-s6-c30.jpg')
css = Book.create(title: 'CSSucks', pages: 420, year: 2019, cover_url: 'https://i1.wp.com/www.developermemes.com/wp-content/uploads/2014/01/CSS-Sucks-TShirt-Meme.jpg?resize=385%2C232')
hunger = Book.create(title: 'The Hunger Games', pages: 374, year: 2008, cover_url: 'https://images.gr-assets.com/books/1447303603l/2767052.jpg')
potter = Book.create(title: 'Harry Potter and the Order of the Phoenix', pages: 870, year: 2003, cover_url: 'https://images.gr-assets.com/books/1546910265l/2.jpg')
mockingbird = Book.create(title: 'To Kill a Mockingbird', pages: 324, year: 1960, cover_url: 'https://images.gr-assets.com/books/1552035043l/2657.jpg')
pride = Book.create(title: 'Pride And Prejudice', pages: 279, year: 1813, cover_url: 'https://images.gr-assets.com/books/1320399351l/1885.jpg')
narnia = Book.create(title: 'The Chronicles of Narnia', pages: 767, year: 1956, cover_url: 'https://images.gr-assets.com/books/1449868701l/11127.jpg')
farm = Book.create(title: 'Animal Farm', pages: 122, year: 1945, cover_url: 'https://images.gr-assets.com/books/1424037542l/7613.jpg')
hobbit = Book.create(title: 'The Hobbit', pages: 310, year: 1937, cover_url: 'https://g.christianbook.com/g/slideshow/9/928227/main/928227_1_ftc.jpg')
fellowship = Book.create(title: 'The Fellowship Of The Rings', pages: 423, year: 1954, cover_url: 'http://images.mentalfloss.com/sites/default/files/styles/width-constrained-728/public/507311-_amazon91jbdarvqml.jpg')
towers = Book.create(title: 'The Two Towers', pages: 352, year: 1954, cover_url: 'http://img1.imagesbn.com/p/9780547952024_p0_v1_s260x420.JPG')
king = Book.create(title: 'The Return Of The King', pages: 416, year: 1955, cover_url: 'https://images-na.ssl-images-amazon.com/images/I/41Qx%2BidkxsL.jpg')

user_1 = User.create(username: "Snozzlebert Chesterfield")
user_2 = User.create(username: "Snorkeldink Crumplehorn")
user_3 = User.create(username: "Fiddlestick Calldispatch")
user_4 = User.create(username: "Bumblebee Cankersore")
user_5 = User.create(username: "Brendadirk Curdlesnoot")
user_6 = User.create(username: "Bedlington Cankersnuff")
user_7 = User.create(username: "Beetlejuice Cragglethatch")
user_8 = User.create(username: "Buckingham Creamsicle")
user_9 = User.create(username: "Burlington Anglerfish")
user_10 = User.create(username: "Bandicoot Crackerdog")
user_11 = User.create(username: "Botany Chuckecheese")
user_12 = User.create(username: "Benadryl Custardbath")
user_13 = User.create(username: "Rinkydink Rainbowfish")
user_14 = User.create(username: "Birdbox Bandersnatch")
user_15 = User.create(username: "Whippersnitch Cottagecheese")
user_16 = User.create(username: "Beezlebub Banglesnatch")
user_17 = User.create(username: "Cadbury Bonaparte")

astronaut.authors << Author.find_or_create_by(name: 'Chris Hadfield')
css.authors << Author.find_or_create_by(name: 'Matt Weiss')
hunger.authors << Author.find_or_create_by(name: 'Suzanne Collins')
potter.authors << Author.find_or_create_by(name: 'J.K. Rowling')
mockingbird.authors << Author.find_or_create_by(name: 'Harper Lee')
pride.authors << Author.find_or_create_by(name: 'Jane Austen')
pride.authors << Author.find_or_create_by(name: 'Anna Quindlen')
narnia.authors << Author.find_or_create_by(name: 'C.S. Lewis')
narnia.authors << Author.find_or_create_by(name: 'Pauline Baynes')
farm.authors << Author.find_or_create_by(name: 'George Orwell')
hobbit.authors << Author.find_or_create_by(name: 'J.R.R. Tolkien')
fellowship.authors << Author.find_or_create_by(name: 'J.R.R. Tolkien')
towers.authors << Author.find_or_create_by(name: 'J.R.R. Tolkien')
king.authors << Author.find_or_create_by(name: 'J.R.R. Tolkien')

user_2.reviews.create(book: astronaut, body: "I have so many good things to say about this book I don't think they'll all fit into one review (for my full review, including my four-year-old's reaction to it, please visit my blog, Cozy Little Book Journal).", headline: 'I have so many good things to say about this book', rating: 5)
user_3.reviews.create(book: astronaut, body: "Have you ever wanted to know the life of an astronaut? How do you even get to be one? What do they do, especially when on earth? Why do they even do it? And how do you combine that with having a family? This wonderful new book will tell you all about it.", headline: 'Have you ever wanted to know the life of an astronaut?', rating: 5)
user_1.reviews.create(book: astronaut, body: 'I hate space for some reason', headline: 'Boo Space', rating: 2)
user_4.reviews.create(book: astronaut, body: 'I also hate space for some reason', headline: 'Boo Space2', rating: 1)
user_5.reviews.create(book: astronaut, body: 'That was way more exciting', headline: "Wasn't The Martian based on a true story?", rating: 3)
user_6.reviews.create(book: astronaut, body: 'I guess they can if you take videos and post them on youtube', headline: 'In space, no one can hear you play guitar', rating: 4)
user_2.reviews.create(book: css, body: "Make Your Psychiatrist Go To The Gym More", headline: "Scary Truths That Will", rating: 1)
user_7.reviews.create(book: css, body: "Agriculture Secretary Thomas J. Vilsack", headline: "Photoshop Tips From", rating: 2)
user_8.reviews.create(book: css, body: "Keep To Themselves", headline: "Secrets Accountants", rating: 3)
user_9.reviews.create(book: css, body: "6 Practical Beard Care Tips", headline: "Scarlett Johansson's", rating: 4)
user_10.reviews.create(book: css, body: "Ernest Moniz Save Skin Care?", headline: "Will Energy Secretary", rating: 5)
user_15.reviews.create(book: css, body: "Thinks About In The Bathroom", headline: "Facts Your Elected Official", rating: 3)
user_2.reviews.create(book: hunger, body: "Secrets From Batman", headline: "Hilarious Dental Care", rating: 1)
user_13.reviews.create(book: hunger, body: "Make Psychologists Feel Ashamed", headline: "Shocking Things That", rating: 3)
user_8.reviews.create(book: hunger, body: "Your Web Designer Feel More Attractive", headline: "Incredible Facts That Will Make", rating: 3)
user_10.reviews.create(book: hunger, body: "Receptionists Won't Tell Their Friends", headline: "Staggering Things", rating: 4)
user_11.reviews.create(book: hunger, body: "Save Trumpet Playing?", headline: "Can Martin Scorsese", rating: 5)
user_12.reviews.create(book: hunger, body: "Surprising Metallurgy Secrets", headline: "Ashton Kutcher's 15", rating: 3)
user_7.reviews.create(book: potter, body: "Your Senator Will Never Learn", headline: "Troubling Truths", rating: 1)
user_13.reviews.create(book: potter, body: "About Lady Gaga", headline: "Scandalous Truths", rating: 4)
user_9.reviews.create(book: potter, body: "Awesome Archery Tips", headline: "Kanye West's Top 6", rating: 3)
user_10.reviews.create(book: potter, body: "That Make Plumbers Nervous", headline: "Horrible Secrets", rating: 3)
user_11.reviews.create(book: potter, body: "Tips From Jay-Z", headline: "Sexy Speed Skating", rating: 4)
user_14.reviews.create(book: potter, body: "About Soldering", headline: "The Embarassing Truth", rating: 5)
user_7.reviews.create(book: mockingbird, body: "CEOs Write In Their Journals", headline: "Hilarious Truths", rating: 1)
user_8.reviews.create(book: mockingbird, body: "David Wichmann's 10 Amazing Halo Tips", headline: "UnitedHealth CEO", rating: 5)
user_10.reviews.create(book: mockingbird, body: "Tips From AT&T CEO Randall L. Stephenson", headline: "Big Wave Surfing", rating: 3)
user_15.reviews.create(book: mockingbird, body: "Your Doctor Is Using Against You", headline: "Unbelievable Facts", rating: 3)
user_12.reviews.create(book: mockingbird, body: "Make Therapists Afraid", headline: "Secrets That", rating: 4)
user_14.reviews.create(book: mockingbird, body: "Make Your Contractor Feel Sexually Confused", headline: "5 Things That Will", rating: 5)
user_13.reviews.create(book: pride, body: "Save Papercraft?", headline: "Will William Shatner", rating: 1)
user_8.reviews.create(book: pride, body: "Physicians Won't Admit", headline: "Amazing Truths", rating: 2)
user_11.reviews.create(book: pride, body: "Boyfriends Eat More Vegetables", headline: "Secrets That Make", rating: 3)
user_12.reviews.create(book: pride, body: "12 Shocking Tree Pruning Tips", headline: "Arnold Schwarzenegger's", rating: 3)
user_16.reviews.create(book: pride, body: "From Bill Gates", headline: "Leaf Blowing Secrets", rating: 4)
user_17.reviews.create(book: pride, body: "Family Doctors Don't Like To Think About", headline: "Mind-Blowing Secrets", rating: 4)
user_7.reviews.create(book: narnia, body: "That Will Make Your Neighbor Angry", headline: "Jaw-Dropping Things", rating: 1)
user_13.reviews.create(book: narnia, body: "That Make Attorneys Feel Aroused", headline: "Surprising Facts", rating: 2)
user_9.reviews.create(book: narnia, body: "About The ghost of Steve Jobs", headline: "The Alarming Truth", rating: 3)
user_10.reviews.create(book: narnia, body: "Top 20 Javascript Tips", headline: "Will Smith's", rating: 4)
user_12.reviews.create(book: narnia, body: "Publicist Is Hiding From You", headline: "Truths Your", rating: 4)
user_17.reviews.create(book: narnia, body: "Your Proctologist Gets Choked Up About", headline: "Terrifying Things", rating: 5)
user_2.reviews.create(book: farm, body: "That Will Make Your Urologist Sleepy", headline: "Frightening Secrets", rating: 5)
user_7.reviews.create(book: farm, body: "Fathers Nervous", headline: "Truths That Make", rating: 5)
user_15.reviews.create(book: farm, body: "Secrets From Johnny Depp", headline: "Unbelievable Frisbee Golf", rating: 3)
user_11.reviews.create(book: farm, body: "About Pet Care", headline: "Awesome Facts", rating: 3)
user_14.reviews.create(book: farm, body: "Are Hiding From You", headline: "Secrets Spouses", rating: 4)
user_17.reviews.create(book: farm, body: "Incredible Microsoft Excel Tips", headline: "Julia Roberts's 15", rating: 5)
user_13.reviews.create(book: hobbit, body: "Save Gymnastics?", headline: "Can Steve Carell", rating: 1)
user_9.reviews.create(book: hobbit, body: "Will Make Your Electrician Mad", headline: "Truths That", rating: 2)
user_10.reviews.create(book: hobbit, body: "From Former President Jimmy Carter", headline: "Rock Climbing Tips", rating: 3)
user_15.reviews.create(book: hobbit, body: "Your Bus Driver Doesn't Know About", headline: "Dangerous Things", rating: 5)
user_12.reviews.create(book: hobbit, body: "Will Make Your Professor Uncomfortable", headline: "Fascinating Facts That", rating: 4)
user_17.reviews.create(book: hobbit, body: "Make Plastic Surgeons Feel Sexy", headline: "Terrifying Truths That", rating: 5)
user_13.reviews.create(book: fellowship, body: "Mother Isn't Telling You", headline: "Scary Secrets Your", rating: 1)
user_8.reviews.create(book: fellowship, body: "Supervisors Won't Tell You", headline: "Embarrassing Things", rating: 2)
user_9.reviews.create(book: fellowship, body: "PowerPoint Tips From Brad Pitt", headline: "Little-Known", rating: 1)
user_15.reviews.create(book: fellowship, body: "Baristas Are Using Against You", headline: "Fascinating Things", rating: 3)
user_11.reviews.create(book: fellowship, body: "Grandmothers Work Harder", headline: "Facts That Make", rating: 1)
user_12.reviews.create(book: fellowship, body: "Of Joke Writing", headline: "The Surprising Secrets", rating: 5)
user_2.reviews.create(book: towers, body: "That Will Make Your Surgeon Stronger", headline: "Terrible Secrets", rating: 1)
user_7.reviews.create(book: towers, body: "Airline Pilot Tweets About", headline: "Truths Your", rating: 2)
user_8.reviews.create(book: towers, body: "Collecting Tips From Robert De Niro", headline: " Jaw-Dropping Stamp", rating: 3)
user_10.reviews.create(book: towers, body: "Employees Don't Know About", headline: "Incredible Things", rating: 3)
user_11.reviews.create(book: towers, body: "Will Make Your Local Politician Work Harder", headline: "Awesome Secrets That", rating: 1)
user_12.reviews.create(book: towers, body: "Save Street Racing?", headline: "Will Leonardo DiCaprio", rating: 5)
user_7.reviews.create(book: king, body: " Waiters Sleepy", headline: "Facts That Make", rating: 1)
user_13.reviews.create(book: king, body: "Will Never Admit", headline: "Truths Your Grandfather", rating: 2)
user_8.reviews.create(book: king, body: "From Chris Pine", headline: "Surprising Tree Climbing Tips", rating: 3)
user_9.reviews.create(book: king, body: "That Make Lawyers Angry", headline: "Amazing Truths", rating: 3)
user_10.reviews.create(book: king, body: "Will Make Your Local Politician Nervous", headline: "Mind-Blowing Secrets That", rating: 2)
user_15.reviews.create(book: king, body: "5 Mind-Blowing Angry Birds Tips", headline: "Netflix CEO Reed Hastings's", rating: 5)
